-- Populate thumbnail_url for videos that don't have one
-- This extracts thumbnail from Cloudinary video URLs

-- For Cloudinary videos, the thumbnail can be generated by:
-- 1. Replacing /upload/ with /upload/so_0,f_jpg/
-- 2. Changing .mp4 to .jpg

-- Update all videos with empty or null thumbnail_url
UPDATE public.videos
SET thumbnail_url = 
  CASE 
    -- If video is from Cloudinary, generate thumbnail URL
    WHEN video_url LIKE '%cloudinary.com%' THEN
      REPLACE(
        REPLACE(video_url, '/upload/', '/upload/so_0,f_jpg/'),
        '.mp4', '.jpg'
      )
    -- If not Cloudinary, set to empty (will show placeholder)
    ELSE ''
  END
WHERE thumbnail_url IS NULL OR thumbnail_url = '';

-- Verify the update
SELECT 
  id,
  title,
  CASE 
    WHEN thumbnail_url IS NOT NULL AND thumbnail_url != '' THEN '✅ HAS THUMBNAIL'
    ELSE '❌ NO THUMBNAIL'
  END as thumbnail_status,
  video_url,
  thumbnail_url
FROM public.videos
ORDER BY created_at DESC
LIMIT 20;
